sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.23.0

install:
  - curl -fsSL get.nextflow.io | bash

script:
  - ./nextflow run . --docker --containers bcftools,fastqc,gatk,multiqc,mutect1,picard,mapreads,runallelecount,runascat,runconvertallelecounts,runmanta,strelka,samtools
